/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adminexploit' at '24/08/18 14:43' with Gradle 3.2.1
 *
 * @author adminexploit, @date 24/08/18 14:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
